### ISSUE TITLE
Xcode 15 iOS duplicate symbol linker error

### ISSUE THREAD

**Issue by noob8boi** [zezo357/pytorch_lite#70]
After updating xcode 14 to 15.2 I started noticing linker issues with pytorch_lite pod. Here I tried building for my physical iPad. 
I understand this might be a XCode Issue instead of it being a package issue.

![image](https://github.com/zezo357/pytorch_lite/assets/91360152/9881133f-00a1-4908-8f02-cb793357ac9e)
![image](https://github.com/zezo357/pytorch_lite/assets/91360152/64a5def0-e3b3-4efc-adc2-3a777907ed86)

**Comment by zezo357** [comment]
I don't know what may be the issue, and since I changed nothing and pytorch didn't change anything, I think it's xcode

But I really don't know 😢

**Comment by noob8boi** [comment]
> I don't know what may be the issue, and since I changed nothing and pytorch didn't change anything, I think it's xcode
> 
> But I really don't know 😢

no problem yea might be a xcode issue... is it working for you in 15.2 version?

**Comment by zezo357** [comment]
I can't check right now, will check when I have some free time

**Comment by noob8boi** [comment]
> I can't check right now, will check when I have some free time

No problem!! just figured it out.. another unrelated pod "async_zip" was causing the error (when installed with pytorch_lite) . I will be closing the issue now :)

**Comment by zezo357** [comment]
> > I can't check right now, will check when I have some free time
> 
> No problem!! just figured it out.. another unrelated pod "async_zip" was causing the error (when installed with pytorch_lite) . I will be closing the issue now :)

Oh, glad you got It figured out, thanks for letting me know ❤️
